export default {
  LOGIN_REQUEST:'USER_LOGIN_REQUEST',
  LOGIN_SUCCESS : 'USER_LOGIN_SUCCESS',
  LOGIN_FAILURE : 'USER_LOGIN_FAILURE',
  AUTO_LOGIN_ATTEMPT : 'USER_AUTO_LOGIN_ATTEMPT',
  LOGOUT : 'USER_LOGOUT',
  FOLLOW_REQUEST : 'USER_FOLLOW_REQUEST',
  FOLLOW_SUCCESS : 'USER_FOLLOW_SUCCESS',
  FOLLOW_FAILURE : 'USER_FOLLOW_FAILURE',
  UNFOLLOW_REQUEST : 'USER_UNFOLLOW_REQUEST',
  UNFOLLOW_SUCCESS : 'USER_UNFOLLOW_SUCCESS',
  UNFOLLOW_FAILURE : 'USER_UNFOLLOW_FAILURE',
}